### ISSUE TITLE
Gunicorn and large file (>500MB)

### ISSUE THREAD

**Issue by ecesarini** [front-matter/invenio-rdm-starter#75]
Hi,
in my invenio-rdm-starter instance I'm trying to upload some files via API or GUI but I'm facing an error.

```bash
oar-web     | IP.IP.IP.IP - - [23/Apr/2025:11:13:43 +0000] "POST /api/records?access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1" 201 4378 "-" "python-requests/2.31.0"
oar-web     | IP.IP.IP.IP - - [23/Apr/2025:11:13:43 +0000] "POST /api/records/0fjd7-bm595/draft/files?access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX HTTP/1.1" 201 841 "-" "python-requests/2.31.0"
oar-web     | [2025-04-23 11:14:13 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:10)
oar-web     | [2025-04-23 11:14:41 +0000] [1] [ERROR] Worker (pid:10) was sent SIGKILL! Perhaps out of memory?
oar-web     | [2025-04-23 11:14:41 +0000] [1011] [INFO] Booting worker with pid: 1011
oar-web     | IP.IP.IP.IP - - [23/Apr/2025:11:14:48 +0000] "GET / HTTP/1.1" 400 135 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
```
I've tried to override the web-container CMD
```yaml
services:
  invenio-rdm-web:
  [...]
  command: /opt/invenio/.venv/bin/python3 /opt/invenio/.venv/bin/gunicorn invenio_app.wsgi:application --bind 0.0.0.0:5000 --workers 4 --access-logfile - --error-logfile - --timeout 600 --graceful-timeout 300
```
but the problem persists. If I set `worker_class = 'gthread'` and `threads = 1` for gunicorn it seems to work but this solution is not feasible for my setup because the invenio GUI gets stuck until the upload ends. 

Is there something else I could try to fix big upload timeout?

Thank you
